#!/bin/bash

if [ $# -ne 2 ]; then
  exit 1
fi

USER_ID=$1
BASE_URL=$2

TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d "{ \"userId\": \"$USER_ID\" }" "${BASE_URL}/api/notifications" | jq -r .token)
if [ -z "$TOKEN" ]; then
  exit 2
fi
curl -s "${BASE_URL}/api/authentication/${TOKEN}" | jq -r .userId
